from rest_framework import serializers
from .models import Notification

class NotificationSerializers(serializers.ModelSerializer):

    class Meta:
        model = Notification

        fields = (
            "id",
            "notification_type",
            "message",
            "is_read",
            "created_at",
        )

        # These values are generated by django
        read_only_fields = (
            "id",
            "created_at",
        )