# Generated by Django 6.1.1 on 2026-09-09 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donorprofile',
            old_name='is_availabe',
            new_name='is_available',
        ),
        migrations.RenameField(
            model_name='donorprofile',
            old_name='nex_eligible_donation',
            new_name='next_eligible_donation',
        ),
    ]
