# Generated by Django 6.1.1 on 2026-09-11 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donors', '0002_rename_is_availabe_donorprofile_is_available_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donorprofile',
            old_name='next_eligible_donation',
            new_name='next_eligible_date',
        ),
    ]
