# Generated by Django 6.1.1 on 2026-09-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_hospitalprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
