from rest_framework import serializers
from .models import BloodRequest

class BloodRequestSerializer(serializers.ModelSerializer):

    # convert the bloodRequest model into JSON
    class Meta:
        model = BloodRequest

        #Fields that will be sent through the API
        fields = (
            "id",
            "requester",
            "hospital",
            "blood_group",
            "units_required",
            "urgency",
            "status",
            "reason",
            "created_at",
        )

        # These fields are generated by the system
        read_only_fields = (
            "id",
            "created_at",
        )