from rest_framework import serializers

from .models import Appointment


class AppointmentSerializer(serializers.ModelSerializer):

    class Meta:
        model = Appointment

        fields = (
            "id",
            "donor",
            "blood_request",
            "hospital",
            "appointment_date",
            "status",
            "notes",
            "created_at",
            "updated_at",
        )

        # These values are generated by Django
        # and should not be entered manually.
        read_only_fields = (
            "id",
            "created_at",
            "updated_at",
        )